version: '3.8'

services:
  arxiv:
    build:
      context: src/servers/arxiv
      dockerfile: Dockerfile
    container_name: arxiv
    ports:
      - "8011:8000"
    env_file:
      - src/servers/arxiv/.env
    volumes:
      - ./src/servers/arxiv:/app

  calculator:
    build:
      context: src/servers/calculator
      dockerfile: Dockerfile
    container_name: calculator
    ports:
      - "8001:8000"
    env_file:
      - src/servers/calculator/.env
    volumes:
      - ./src/servers/calculator:/app

  coding:
    build:
      context: src/servers/coding
      dockerfile: Dockerfile
    container_name: coding
    ports:
      - "8002:8000"
    env_file:
      - src/servers/coding/.env
    volumes:
      - ./src/servers/coding:/app
  dataanalysis:
    build:
      context: src/servers/dataAnalysis
      dockerfile: Dockerfile
    container_name: dataAnalysis
    ports:
      - "8003:8000"
    env_file:
      - src/servers/dataAnalysis/.env
    volumes:
      - ./src/servers/dataAnalysis:/app
  documentgrader:
    build:
      context: src/servers/documentGrader
      dockerfile: Dockerfile
    container_name: documentGrader
    ports:
      - "8004:8000"
    env_file:
      - src/servers/documentGrader/.env
    volumes:
      - ./src/servers/documentGrader:/app
  router:
    build:
      context: src/servers/router
      dockerfile: Dockerfile
    container_name: router
    ports:
      - "8005:8000"
    env_file:
      - src/servers/router/.env
    volumes:
      - ./src/servers/router:/app
  vectordb:
    build:
      context: src/servers/vectordb
      dockerfile: Dockerfile
    container_name: vectordb
    ports:
      - "8006:8000"
    env_file:
      - src/servers/vectordb/.env
    volumes:
      - ./src/servers/vectordb:/app
  websearch:
    build:
      context: src/servers/websearch
      dockerfile: Dockerfile
    container_name: websearch
    ports:
      - "8007:8000"
    env_file:
      - src/servers/websearch/.env
    volumes:
      - ./src/servers/websearch:/app
  hallucinationgrader:
    build:
      context: src/servers/hallucinationGrader
      dockerfile: Dockerfile
    container_name: hallucinationGrader
    ports:
      - "8008:8000"
    env_file:
      - src/servers/hallucinationGrader/.env
    volumes:
      - ./src/servers/hallucinationGrader:/app
  responsegenerator:
    build:
      context: src/servers/responseGenerator
      dockerfile: Dockerfile
    container_name: responseGenerator
    ports:
      - "8009:8000"
    env_file:
      - src/servers/responseGenerator/.env
    volumes:
      - ./src/servers/responseGenerator:/app
  graphendpoint:
    build:
      context: src/graph
      dockerfile: Dockerfile
    container_name: graphendpoint
    ports:
      - "8010:8000"
    env_file:
      - src/graph/.env
    volumes:
      - ./src/graph:/app